import './globals.css'
import type { Metadata } from 'next'
import { Montserrat, Oswald } from 'next/font/google'
import { FooterWrapper } from '@/components/layout/FooterWrapper'

const montserrat = Montserrat({ 
  subsets: ['latin'],
  weight: ['400', '500', '600', '700'],
  variable: '--font-montserrat',
  display: 'swap',
})

const oswald = Oswald({
  subsets: ['latin'],
  weight: ['400', '500', '600', '700'],
  variable: '--font-oswald',
  display: 'swap',
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={`${montserrat.variable} ${oswald.variable}`}>
        {children}
        <FooterWrapper />
      </body>
    </html>
  )
}
